---
deployment:
  tasks:
    - php ./composer install
    - php artisan migrate
    - php artisan view:clear
    - php artisan route:clear
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan optimize:clear
